version: '{build}'
os: Windows Server 2012
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - ps: |
      If ($env:Platform -Match "x86") {
        $env:PCRE_PLATFORM="Win32"
        $env:JAVA_HOME="c:/Program Files (x86)/Java/jdk1.8.0"
        $env:MSBuildDir="C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe"
        $env:VCVARS_PLATFORM="x86"
        $env:LANG_PLATFORM=""
      } Else {
        $env:PCRE_PLATFORM="x64"
        $env:JAVA_HOME="c:/Program Files/Java/jdk1.8.0"
        $env:MSBuildDir="C:/Program Files/MSBuild/14.0/Bin/msbuild.exe"
        $env:VCVARS_PLATFORM="amd64"
        $env:LANG_PLATFORM="-x64"
      }	  
  - cmd: appveyor DownloadFile https://github.com/nunit/nunit/releases/download/3.0.0-beta-3/nunit-3.0.0-beta-3.zip
  - cmd: 7z x -oC:\Tools\NUnit3 nunit-3.0.0-beta-3.zip > NUL
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;C:\Tools\NUnit3\bin;%PATH%
  - cmd: SET
build_script:
  - mvn clean install -DvsBin="C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe"
after_test:
  - cmd: ProjectCheckerRunner\nuget\nuget.exe pack  ProjectCheckerRunner\nuget\MsbuildAutomationHelper.nuspec
  - cmd: ProjectCheckerRunner\nuget\nuget.exe pack  ProjectCheckerRunner\nuget\MSbuildPackageDiagramCreator.nuspec
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
artifacts:
  - path: 'sonar-msbuild-plugin/target/*.jar'
    name: sonar-msbuild-plugin
  - path: 'sonar-msbuild-plugin/target/*.nupkg'
    name: sonar-msbuild-plugin-nugets
